#!/usr/bin/env python3
"""Shared Kimi API client - auto-generated by harbor-self-optimization task"""
import os
import sys
import requests

KIMI_API_KEY = os.environ.get("KIMI_API_KEY", "")
KIMI_URL = os.environ.get("KIMI_URL", "").rstrip("/")
KIMI_MODEL = os.environ.get("KIMI_MODEL", "")

def call_kimi(messages, max_tokens=8000, temperature=0.2, timeout=60):
    """Call Kimi API (OpenAI-compatible)."""
    if not all([KIMI_API_KEY, KIMI_URL, KIMI_MODEL]):
        raise ValueError("Missing required env vars: KIMI_API_KEY, KIMI_URL, KIMI_MODEL")
    
    url = f"{KIMI_URL}/chat/completions"
    headers = {
        "Authorization": f"Bearer {KIMI_API_KEY}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": KIMI_MODEL,
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
    }
    resp = requests.post(url, headers=headers, json=payload, timeout=timeout)
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"]
